### ISSUE TITLE
Angular could not find provider for Store when importing DucksModule.register(...)

### ISSUE THREAD

**Issue by lutzleonhardt** [co-IT/co-it#1]
At first, thank you for this great framework, a really timesaver :)
I've started to integrate the current version in an anglular 6 app. I know it's not finished yet but still usable. I've cloned and build it locally and installed it as a local npm repo.

This is the simple structure:
![image](https://user-images.githubusercontent.com/11898898/45882992-1b04e700-bdb0-11e8-814b-f570d9128aa8.png)

Here you see the duck code for my component `transactions-page.ducks.ts` :

```
import { createReducerFrom, wireUpActions } from '@co-it/ngrx-ducks'
import { Action } from '@ngrx/store'

export class TransactionsPageState {
  filter: TransactionsPageFilter = new TransactionsPageFilter()
}

export class TransactionsPageFilter {
  byAccounts: string[] = []
}

export class TransactionsPage {
  public addAccountToFilter(state: TransactionsPageState, payload: string): typeof state {
    return {
      ...state,
      filter: {
        ...state.filter,
        byAccounts: [ ...state.filter.byAccounts, payload ],
      },
    }
  }
}

export const transactionsPageActions = () => wireUpActions(TransactionsPage, {
  addAccountToFilter: '[TransactionsPage] Add account to filter',
})

const initialState = new TransactionsPageState()
export const transactionsPageReducer = (state = initialState, action: Action) =>
  createReducerFrom(transactionsPageActions())(state, action)

```

Here the code of my component using the duck `transactions-page.component.ts`:

```
@Component({
  selector: 'app-transactions-page',
  templateUrl: './transactions-page.component.html',
  styleUrls: [ './transactions-page.component.scss' ],
})
export class TransactionsPageComponent implements OnInit {

  constructor(@Inject(TransactionsPage) private actions: Ducks<TransactionsPage>) {
  }

  public ngOnInit() {
    this.actions.addAccountToFilter('New Account')
  }

}
```

The feature store is registered in `bank.module.ts`:
```
@NgModule({
  imports: [
    CommonModule,
    StoreModule.forFeature('bank', reducers),

    BankRoutingModule,

    // pages
    AccountsPageModule,
    TransactionsPageModule,

  ],
  declarations: [],
})
export class BankModule {}
```

The problematic part is in `transactions-page.module.ts`:

```
@NgModule({
  imports: [
    CommonModule,
    DucksModule.register([
      {
        duck: TransactionsPage,
        use: transactionsPageActions,
      },
    ]),
  ],
  declarations: [ TransactionsPageComponent ],
  exports: [ TransactionsPageComponent ],
})
export class TransactionsPageModule {}
```
There is a DI error, angular could not find a provider for the ngrx store:

![image](https://user-images.githubusercontent.com/11898898/45883269-dd548e00-bdb0-11e8-99f1-6cfd5c593d3b.png)

The error does not happen when registering the duck manually:

![image](https://user-images.githubusercontent.com/11898898/45883335-0bd26900-bdb1-11e8-8ea0-4ae82328ea70.png)

And then it's working like a charm:

![image](https://user-images.githubusercontent.com/11898898/45883350-1b51b200-bdb1-11e8-91e1-6c182a3eb9f9.png)

Here are the deps of my package.json:

```
 "dependencies": {
    "@angular/animations": "^6.1.8",
    "@co-it/ngrx-ducks": "file:../co-it/ngrx/ducks/dist",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@progress/kendo-angular-inputs": "^3.2.1",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-theme-default": "latest",
    "rxjs-compat": "^6.0.0"
  },

```

**Comment by GregOnNet** [comment]
Hi @lutzleonhardt,

thank you so much for your feedback.
It made me publish the first version of @ngrx-ducks.

## Install via npm

You are now able to install the package running `npm i @co-it/ngrx-ducks`.

- Please note that this is still a prerelease.
- The documentation is outdated since there was an issue with AoT

## Demo

You will find a running sample application here: [ngrx-ducks-demo](https://github.com/GregOnNet/ngrx-ducks-demo)

## HowTo - Register Ducks

The only thing that has been changed is how to register Ducks.
I had to remove the `DucksModule`-approach since this would break AoT.

For now please use a provider to register `Ducks`.

```ts
// This snippet shows the AppModule.
// It also should work inside a feature module.
@NgModule({
  ...
  imports: [
    StoreModule.forRoot(reducers, { metaReducers }),
    // ...
  ],
  providers: [
    {
      provide: Counter,
      useFactory: function(store) {
        return createDucks(counterActions, store);
      },
      deps: [Store]
    }
  ]
})
export class AppModule {}
```

Please feel free to ask any further questions.

Kinds
Greg

**Comment by lutzleonhardt** [comment]
Hello @GregOnNet,
thanks for your detailed answer and your great work.

One another question (should I open another Issue?):
What about specifying a payload when dispatching an effect action, i.e.:

`this.counter.load.dispatch({skip: 10, take: 20});`

The only alternative way now is to write the values in the store before 
dispatching this action (and accessing these values with withLatestFrom() in the effect).

Thanks in advance
Lutz

**Comment by GregOnNet** [comment]
Good question!
Often you just want to return the action object since an Effect will dispatch the action.
In this case, you can use the method `plain`. This is just the action creator.

```ts
// Sample
@Injectable()
export class CounterEffects {
  @Effect()
  setCounterTo5 = this.actions$.pipe(
    ofType(this.counter.loadAll.type),
    map(() => {
      return this.counter.set.plain(100000); // yields { type: '[Counter] Set', payload: 100000 }
    })
  );

  constructor(
    private actions$: Actions,
    @Inject(Counter) private counter: Ducks<Counter>

  ) {}
}
```
_Source: https://github.com/GregOnNet/ngrx-ducks-demo/blob/master/src/app/reducers/counter.effects.ts#L13_

Sometimes you want to dispatch another action as a side effect inside of an `Effect`.
Then just use the duck as you do inside your Components.


P.S.: I think I will rename the method `plain` to `action` when version 1.0 is released.

**Comment by lutzleonhardt** [comment]
Thanks for your answer. But is there a possibility to let the component set the payload (in you sample the value 100000) for the side effect? The only possibility would be to write it in the store before, right?

**Comment by lutzleonhardt** [comment]
BTW I use ngrx-ducks together with ngrx/entity and immer and it works like a charm. No more boilerplate action/creator and reducer code :) 👍

**Comment by GregOnNet** [comment]
I am so happy that you try everything out.

Back to your question.
Maybe we misunderstand each other.

|Code|What it does|
|-|-|
|`this.counter.set(1)`|This **dispatches**  an Action `{ type: '[Counter] Set', payload: 1 }`|
|`const action = this.counter.set.plain(1)`|This creates an Action `{ type: '[Counter] Set', payload: 1 }`. **No dispatch** here. |

It is totally up to you how you use this API.
Do you see a use case that is not covered by ngrx-ducks yet?

**Your question**
> But is there a possibility to let the component set the payload

*The provided method of the duck will set the paylaod for you and adds the action type.*

**Comment by GregOnNet** [comment]
Now I think to get your question. :D
You are totally right.
For now it is not possible to add a payload to an Action that is passed to an Effect.

Good catch!

I should add this possibility. 
The hard thing here is how I can type the corresponding payload...

**Comment by lutzleonhardt** [comment]
Yes, that’s my point :)
For the start it could be simple any, but I have no better idea at the moment. I like the idea, that effect actions are simple strings in the duck class.

**Comment by GregOnNet** [comment]
I have an idea.
I will try to implement something like the following:

```ts
export class Counter {
  loadAll = effect<number>('[Counter] Some Async Stuff');
}
```

This API has two benefits.
Newcomers will see that the defined property has something to do with `Effects`.
The generic parameter tells which payload has to be passed.

I can use the `effect` method to pass through the type information.
I will check if this works.

Thanks a lot!

**Comment by lutzleonhardt** [comment]
Yes, I got the idea. Sounds good to me.

**Comment by GregOnNet** [comment]
Good evening sir,

version 0.3.2 introduces a breaking change.
Actions triggering Effects now have to be declared with the new helper `effect`.

```ts
export class Counter {
  readonly noPayload = effect('[Counter] Has no Payload');
  readonly withPayload = effect<number>('[Counter] Has number as Payload');
}
```
*see: https://github.com/GregOnNet/ngrx-ducks-demo/blob/master/src/app/reducers/counter.actions.ts#L6*

`effect` allows defining actions for Effects in one line.
Furthermore, we use TypeScript's compiler to have autocompletion support whether we specified a payload type or not:
![image](https://user-images.githubusercontent.com/444278/45980028-32aeca80-c051-11e8-9e20-c2c13eff70a9.png)

I hope you find this useful. 🎉

**Comment by lutzleonhardt** [comment]
Well done. Looks great 👍🏻 I will give it a try. Thanks so much

**Comment by GregOnNet** [comment]
I close this issue for now.
If you have any further questions or recommendations do not hesitate to open a new issue. :)
