### ISSUE TITLE
[ngrx-ducks] Landing Page

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/co-it#12]
## Story

NgRx Ducks offers several benefits for ngrx users:

- Higher Maintainability
- Less Code to write
- Less Confusion concerning Actions
- Easier API

To make these points more visible to developers we should add a landing page highlighting the best features of ngrx-ducks.

Please find the first design attempt below.
As always feedback is very welcome.

![ngrx-ducks](https://user-images.githubusercontent.com/444278/53317945-d84eba00-38cd-11e9-952d-8ec19d37f26b.png)

## ToDo

- [ ] Add section for `@Effect` integration

**Comment by mhoyer** [comment]
Good job and a nice layout. But I have some ideas to improve it further:

The yellowish foreground looks a bit "_dirtyish_" on that dark purple background to me. Maybe a bit more saturation (for the font) and brightness can help? Did you try out some color wheels to find a good pair of colors?

The page describes only the **how**, but not the **why**. So maybe adding a side-by-side comparison of the _traditional way_ of creating reducers and actions may be helpful?

And a last small issue. I am missing the definition of `CounterState` type in your examples. Maybe this also makes sense to see it before first use?

**Comment by mhoyer** [comment]
Oh, and to show the power of Typescript and code completion you may think about one or more little animated GIFs?
