### ISSUE TITLE
[ngrx-ducks] filter operator for @Effect

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/co-it#13]
## Story

Until now, we need to manually set the type of the payload that is passed to an @Effect since only the action type is provided as string.

```ts
// declare type of payload manually using ActionOf<T> helper

@Effect()
load = this.actiosn$.pipe(ofType<ActionOf<number>>(this.counter.set.type));
```

With an own operator it is possible to infer the type of the payloar automatically.

```ts
// payload will be inferred automatically

@Effect()
load = this.actiosn$.pipe(filterType(this.counter.set));

// multiple types
@Effect()
load = this.actiosn$.pipe(filterType([this.counter.set, this.counter.load]));
```

## Benefits

- Reduces code
- Prevent bugs introduced by wrong type declarations

## Thoughts

The operator should be named differently to ngrx's `ofType` avoiding name collisions.
I am not sure how the name of the operator should be.

Possible names could be:

- filterType
- whereType
- where
- selectType

**Comment by GregOnNet** [comment]
@skydever What do you think about this?

**Comment by GregOnNet** [comment]
🚀 This feature has been released with ngrx-ducks **7.5.1**

You can now use the operator `whereType` that automatically infers the type of the payload that is processed.

https://stackblitz.com/edit/ngrx-ducks?embed=1&file=src/app/store/counter/counter.effects.ts

Sorry @skydever, I could not wait for your feedback. :-D

**Comment by skydever** [comment]
Sorry that I could not respond earlier (a lot is going on lately), but it seems that I have nothing to add - this is just great and will help a lot 🎉 The choice of the name is totally fine!

keep up with the great work!! 👍

**Comment by GregOnNet** [comment]
Thank you!
