### ISSUE TITLE
Move ngrx-ducks to own repository

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/co-it#15]
It turned out that a company monorepo is not the right thing for us at co-IT.
We only want to group those packages to together that are release together.

That's why we will move the following packages to a new monorepo (https://github.com/co-IT/ngrx-ducks):

- @co-it/ngrx-ducks
- @co-it-ngrx-ducks-schematics
- ngrx-ducks (VS Code Snippets)

**Comment by GregOnNet** [comment]
This task can be done after finishing #5.

**Comment by GregOnNet** [comment]
NgRx Ducks have been moved to https://github.com/co-it/ngrx-ducks.

//cc @skydever

**Comment by skydever** [comment]
... and the list of contributors is already growing, very nice :+1:
