### ISSUE TITLE
Upgraded from 8.0.1-rc.0 to 8.0.1

### ISSUE THREAD

**Issue by guisperandio** [co-IT/co-it#18]
After the update the application can't find the module on node_module.

**Comment by guisperandio** [comment]
Issued fixed changing the path from '@co-it/ngrx-ducks' to '@co-it/ngrx-ducks/dist'

**Comment by guisperandio** [comment]
But i think that isn't the best solution, maybe add a index.ts on root folder, or a public api there. TO import the module using @co-it/ngrx-ducks only

**Comment by GregOnNet** [comment]
Hi @guisperandio,

sorry for the late response.
NgRx has been moved to another repository: https://github.com/co-IT/ngrx-ducks

Nevertheless, you are totally right.
The release 8.01 was broken.
Luckily, this issue has already been fixed .
