### ISSUE TITLE
[ngrx-ducks] @ngrx/entity store & crud actions

### ISSUE THREAD

**Issue by skydever** [co-IT/co-it#7]
Hi there!

The idea is to simplify the creation of actions for the **@ngrx/entity** adaptor collection methods. I can think of this in two ways:

1. Create a <T>base class for `Ducks` that will rely on **@ngrx/entity**, having abstract values for:
  * `[source]` prefix ... will result to:
    * `[source] Add $EntityClass`
    * `[source] Update $EntityClass`
    * `[source] Delete $EntityClass`
    * ... all **@ngrx/entity** adaptor methods ...
  * `entityClass` = T
  * `selectId`
  * `sortComparer`
  * `stateExtendingProperties`

2. Create a `Duck` decorator that will get the above abstract values via decorator properties `@EntityDuck({ ...config.... })` and create the methods *magically* under the hood

What do you think? How could this be achieved best?

I will be thankful for ideas!

ps: maybe this can can be extended to include default rest calls via effects, something like **ngrx-data** does - creating default crud operations *magically*. maybe a corresponding effect decorator to add default crud effects/http calls relying on a EntityDucks based class, like 
```typescript
@EntityDuckEffects({ 
  duck: EntityDuck, 
  api: { 
    baseUrl: '/api/entity', 
    postUrl?: string; ... 
  }
})
export class EntityEffects {
}
```
or
```typescript
export class EntityEffects extends NgrxEntityDuckEffects {
  duck = EntityDuck; // is always injected inside a DuckEffect class
  api = {...};
}
```

**Comment by skydever** [comment]
... and use the new `@InitialState()` decorator #3 👍

**Comment by GregOnNet** [comment]
Ah, now I got it! Thank you for the more detailed description.
I really need to think about how ngrx/entity could be automatically integrated into ngrx-ducks.

> First I need to finish the basic decorator support. It is like rewriting the whole library. 😄


## ngrx-auto-entity | Further Reading

Briebug also works on a library reducing boilerplate for ngrx/entity: [ngrx-auto-entity](https://www.npmjs.com/package/@briebug/ngrx-auto-entity)
It seems that they also create Actions based on a convention as you have described.

In the end you need to do a `store.dispatch` in the Component where in my opinion **ngrx/ducks** provides a better experience.

**Comment by skydever** [comment]
I also think that **ngrx/ducks** provide a better experience, and that is why I played around with the *base class concept* a bit - maybe you have some valuable input for me?

I created an `abstract EntityDuck<Entity, State extends EntityState<Entity>>` class with the following properties:

* `entityAdapter = createEntityAdapter<Entity>({ ... protected methods for selectId, sortComparer ...});`
* *All* crud methods from `EntityAdapter` marked with the decorator like `@Action('[CREATE] ... will be overwritten') create(state: State, e: Entity): State => this.adapter.addOne(e);`, to create the `wiredAction`

Then I do the setup like this:
* The `Duck` is extending the base class `MyDuck extends EntityDuck<MyEntity, MyDuckState>`
* an additional method to provide it `ducksify(extendWithEntityActions(MyDuck, 'MyDuckFeature', 'MyEntity'), store)`
* the method `extendWithEntityActions(class, featureName, entityName)`:
  * `Object.getOwnPropertyNames()` does not list the functions from the base class, so the self-dispatching actions do not work, this methods adds the `EntityDuck` functions to the `MyDuck` prototype, by pointing to the methods of the base class prototype `Object.getPrototypeOf()`. Like this `class.prototype.create = Object.getPrototypeOf(class.prototype).create;` and I set the action types for the `wiredAction` based on the given values `featureName` and `entityName` like this `class.prototype.create.wiredAction.type='[$(featureName) $(entityName)] Add $(entityName)'`

What do you think about that approach? I am not sure about typescript side effects, if there are some. Still have to find the correct typing for the given `class`, it should extend the `EnityDuck` class instead of `any` 😃, having a typed intellisense here would be nice (including `.create.wiredAction` because I do that mapping hardcoded ... maybe I can change this as well, making it a bit less code ...)

***will correct the syntax, not having the code at hand***

**Comment by GregOnNet** [comment]
I think I can imagine what you want to do.
But to be sure I need some sample code.

Do we want to discuss it tomorrow at our call?

**Comment by skydever** [comment]
Would be great :+1: I try to create a stackblitz sample for it.

**Comment by skydever** [comment]
... and here is the [stackblitz  sample](https://stackblitz.com/edit/ngrx-ducks-entity?file=src%2Fapp%2Fstore%2Fmy-entities%2Fmy-entity.duck.ts) :runner:

**Comment by skydever** [comment]
Some use cases for my `EntityDuck` solution came up lately, and we discussed it a bit at our call @GregOnNet , but I think I have some more questions on that topic. Maybe you have some thoughts on them, would be great to hear your opinion.

I like the solution for simple `Entities`. You can split the *concerns* quite well by creating a single `Duck` that is just managing this one `Entity` - but this leads to a lot of actions, and I am not sure what I should think of it at the moment. As you mentioned at the call, you are limited to the actions that will be created automatically, there is no possibility for a eg. hook to set the loading state in addition to the `entityAdapter` modification, you have to dispatch a 2nd action for that. In some cases I want access to the `entityAdapter` directly. The inheritance is not as it should be shomehow, `this` gets confused if you call functions from a base class, or if you do a deeper inheritance and call that. Not quite sure how to handle hat correctly, what is possible (?)

I thought about something like that when I have multiple lists of `Entities` inside of one `Duck`:
```typescript
// pseudo code not verified
abstract class EntityDuck<EntityStateMapping> {
  entityAdapterManager: EntityAdapterManger<EntityStateMapping>;
}

@EntityDucksify({
  initialState: {
    entity: initialEntityState(),
    entity2: initialEntityState()
  }
})
class MyDuck extends EntityDuck {
  @Action('[Entity All] Loaded')
  addAllEntities(state, entities) {
    return {
      this.entityAdapterManager.get('state.path.to.entity.state').addAll(state, entities),
      isLoading: false
    };
  }

  @Action('[Entity2 All] Loaded')
  addAllEntity2s(state, entity2s) {
    return {
      this.entityAdapterManager.get('state.path.to.entity2.state').addAll(state, entity2s),
      isPreLoading: false
    };
  }
}
```

... or some other kind of `MasterDuck` to interact with isolated `Ducks`?

Do you want to integrate the simple `EntityDuck` solution, or have other plans of how to integrate **@ngrx/entity**?

**Comment by GregOnNet** [comment]
Hey,

I think the best way to get our head around this problem would be to set up another Google Hangout, where we discuss your needs while analysing your code base. :)

I need to see a real-life example to come up with a sufficient solution.

Do you mind to show me some parts of your code?

**Comment by skydever** [comment]
Thx a lot for this offer, but I think I have to walk through that again myself first - seems like I got a few things wrong. It was just an idea, but when I look at it now 🤔 

If I have to manage multiple lists the `EntityDuck` is no solution - it just generates `EntityAdapter` actions for one `Entity` to avoid writing them by hand, if it is the only thing I need. It is not very flexible, as mentioned - so my conclusion is: get something for free if it is enough, else create the `EntityAdapter` yourself and have flexibility ... I see no benefit in wrapping the `EntityAdapter` anymore ...

... and I am not surea about the idea of a `MetaReducerDuck`, have to walk through some use cases ... I guess what I am looking for are `Effects` already, I listen for `Actions` from multiple `Ducks`, get data from multiple `Ducks` and use multiple `Ducks` for the `Store` manipulation ... not having a specific use case in mind, just in general ...

**Comment by GregOnNet** [comment]
I close this issue for now, since you managed to write an ngrx/entity Decorator on your own.

Please file another issue if you need further support.
